//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 11:01:42 AM IST 
//


package com.mycompany.holiday.modelcom.pzv.dataload.model.dana.aftermarket.customermaster;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TotalCustomerReceived" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="TotalCustomersLoaded" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalCustomerReceived",
    "totalCustomersLoaded"
})
@XmlRootElement(name = "LoadCustomerMasterResponse")
public class LoadCustomerMasterResponse {

    @XmlElement(name = "TotalCustomerReceived")
    protected long totalCustomerReceived;
    @XmlElement(name = "TotalCustomersLoaded")
    protected long totalCustomersLoaded;

    /**
     * Gets the value of the totalCustomerReceived property.
     * 
     */
    public long getTotalCustomerReceived() {
        return totalCustomerReceived;
    }

    /**
     * Sets the value of the totalCustomerReceived property.
     * 
     */
    public void setTotalCustomerReceived(long value) {
        this.totalCustomerReceived = value;
    }

    /**
     * Gets the value of the totalCustomersLoaded property.
     * 
     */
    public long getTotalCustomersLoaded() {
        return totalCustomersLoaded;
    }

    /**
     * Sets the value of the totalCustomersLoaded property.
     * 
     */
    public void setTotalCustomersLoaded(long value) {
        this.totalCustomersLoaded = value;
    }

	@Override
	public String toString() {
		return "LoadCustomerMasterResponse [totalCustomerReceived=" + totalCustomerReceived + ", totalCustomersLoaded="
				+ totalCustomersLoaded + "]";
	}
}
