//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 11:01:42 AM IST 
//


package com.mycompany.holiday.modelcom.pzv.dataload.model.dana.aftermarket.customermaster;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mycompany.holiday.modelcom.pzv.dataload.model.dana.aftermarket.customermaster package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mycompany.holiday.modelcom.pzv.dataload.model.dana.aftermarket.customermaster
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadCustomerMasterRequest }
     * 
     */
    public LoadCustomerMasterRequest createLoadCustomerMasterRequest() {
        return new LoadCustomerMasterRequest();
    }

    /**
     * Create an instance of {@link CustomerMaster }
     * 
     */
    public CustomerMaster createCustomerMaster() {
        return new CustomerMaster();
    }

    /**
     * Create an instance of {@link LoadCustomerMasterResponse }
     * 
     */
    public LoadCustomerMasterResponse createLoadCustomerMasterResponse() {
        return new LoadCustomerMasterResponse();
    }

}
