//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 05:21:05 PM IST 
//


package com.pzv.dataload.model.dana.aftermarket.customermaster;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerMaster complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerMaster"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustomerNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="CustomerName01" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CustomerName02" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CustomerGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CustomerPriceGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ChannelCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SubChannelCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Company" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Branch" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AddressLine01" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AddressLine02" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Zip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Phone01" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Phone02" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Territory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Contact" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ShipVia" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Terms" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HandlerCode01" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HandlerCode02" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CreditExempt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IsShipOnly" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IsHold" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IsBackOrderAllow" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IsInternal" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IsVolvo" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IsHotShot" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerMaster", propOrder = {
    "customerNo",
    "isActive",
    "customerName01",
    "customerName02",
    "customerGroup",
    "customerPriceGroup",
    "channelCode",
    "subChannelCode",
    "company",
    "branch",
    "addressLine01",
    "addressLine02",
    "city",
    "state",
    "zip",
    "country",
    "phone01",
    "phone02",
    "fax",
    "territory",
    "email",
    "website",
    "contact",
    "shipVia",
    "terms",
    "freight",
    "handlerCode01",
    "handlerCode02",
    "creditExempt",
    "isShipOnly",
    "isHold",
    "isBackOrderAllow",
    "isInternal",
    "isVolvo",
    "isHotShot"
})
public class CustomerMaster {

    @XmlElement(name = "CustomerNo", required = true)
    protected String customerNo;
    @XmlElement(name = "IsActive")
    protected boolean isActive;
    @XmlElement(name = "CustomerName01", required = true)
    protected String customerName01;
    @XmlElement(name = "CustomerName02", required = true)
    protected String customerName02;
    @XmlElement(name = "CustomerGroup", required = true)
    protected String customerGroup;
    @XmlElement(name = "CustomerPriceGroup", required = true)
    protected String customerPriceGroup;
    @XmlElement(name = "ChannelCode", required = true)
    protected String channelCode;
    @XmlElement(name = "SubChannelCode", required = true)
    protected String subChannelCode;
    @XmlElement(name = "Company", required = true)
    protected String company;
    @XmlElement(name = "Branch")
    protected int branch;
    @XmlElement(name = "AddressLine01", required = true)
    protected String addressLine01;
    @XmlElement(name = "AddressLine02", required = true)
    protected String addressLine02;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "Zip", required = true)
    protected String zip;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "Phone01", required = true)
    protected String phone01;
    @XmlElement(name = "Phone02", required = true)
    protected String phone02;
    @XmlElement(name = "Fax", required = true)
    protected String fax;
    @XmlElement(name = "Territory", required = true)
    protected String territory;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "Website", required = true)
    protected String website;
    @XmlElement(name = "Contact", required = true)
    protected String contact;
    @XmlElement(name = "ShipVia", required = true)
    protected String shipVia;
    @XmlElement(name = "Terms", required = true)
    protected String terms;
    @XmlElement(name = "Freight", required = true)
    protected String freight;
    @XmlElement(name = "HandlerCode01", required = true)
    protected String handlerCode01;
    @XmlElement(name = "HandlerCode02", required = true)
    protected String handlerCode02;
    @XmlElement(name = "CreditExempt", required = true)
    protected String creditExempt;
    @XmlElement(name = "IsShipOnly")
    protected boolean isShipOnly;
    @XmlElement(name = "IsHold")
    protected boolean isHold;
    @XmlElement(name = "IsBackOrderAllow")
    protected boolean isBackOrderAllow;
    @XmlElement(name = "IsInternal")
    protected boolean isInternal;
    @XmlElement(name = "IsVolvo")
    protected boolean isVolvo;
    @XmlElement(name = "IsHotShot")
    protected boolean isHotShot;

    /**
     * Gets the value of the customerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * Sets the value of the customerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNo(String value) {
        this.customerNo = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the customerName01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName01() {
        return customerName01;
    }

    /**
     * Sets the value of the customerName01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName01(String value) {
        this.customerName01 = value;
    }

    /**
     * Gets the value of the customerName02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName02() {
        return customerName02;
    }

    /**
     * Sets the value of the customerName02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName02(String value) {
        this.customerName02 = value;
    }

    /**
     * Gets the value of the customerGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerGroup() {
        return customerGroup;
    }

    /**
     * Sets the value of the customerGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerGroup(String value) {
        this.customerGroup = value;
    }

    /**
     * Gets the value of the customerPriceGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPriceGroup() {
        return customerPriceGroup;
    }

    /**
     * Sets the value of the customerPriceGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPriceGroup(String value) {
        this.customerPriceGroup = value;
    }

    /**
     * Gets the value of the channelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * Sets the value of the channelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelCode(String value) {
        this.channelCode = value;
    }

    /**
     * Gets the value of the subChannelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubChannelCode() {
        return subChannelCode;
    }

    /**
     * Sets the value of the subChannelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubChannelCode(String value) {
        this.subChannelCode = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     */
    public int getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     */
    public void setBranch(int value) {
        this.branch = value;
    }

    /**
     * Gets the value of the addressLine01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine01() {
        return addressLine01;
    }

    /**
     * Sets the value of the addressLine01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine01(String value) {
        this.addressLine01 = value;
    }

    /**
     * Gets the value of the addressLine02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine02() {
        return addressLine02;
    }

    /**
     * Sets the value of the addressLine02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine02(String value) {
        this.addressLine02 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the phone01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone01() {
        return phone01;
    }

    /**
     * Sets the value of the phone01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone01(String value) {
        this.phone01 = value;
    }

    /**
     * Gets the value of the phone02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone02() {
        return phone02;
    }

    /**
     * Sets the value of the phone02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone02(String value) {
        this.phone02 = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the territory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerritory() {
        return territory;
    }

    /**
     * Sets the value of the territory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerritory(String value) {
        this.territory = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the shipVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipVia() {
        return shipVia;
    }

    /**
     * Sets the value of the shipVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipVia(String value) {
        this.shipVia = value;
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerms(String value) {
        this.terms = value;
    }

    /**
     * Gets the value of the freight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreight() {
        return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreight(String value) {
        this.freight = value;
    }

    /**
     * Gets the value of the handlerCode01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandlerCode01() {
        return handlerCode01;
    }

    /**
     * Sets the value of the handlerCode01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandlerCode01(String value) {
        this.handlerCode01 = value;
    }

    /**
     * Gets the value of the handlerCode02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandlerCode02() {
        return handlerCode02;
    }

    /**
     * Sets the value of the handlerCode02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandlerCode02(String value) {
        this.handlerCode02 = value;
    }

    /**
     * Gets the value of the creditExempt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditExempt() {
        return creditExempt;
    }

    /**
     * Sets the value of the creditExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditExempt(String value) {
        this.creditExempt = value;
    }

    /**
     * Gets the value of the isShipOnly property.
     * 
     */
    public boolean isIsShipOnly() {
        return isShipOnly;
    }

    /**
     * Sets the value of the isShipOnly property.
     * 
     */
    public void setIsShipOnly(boolean value) {
        this.isShipOnly = value;
    }

    /**
     * Gets the value of the isHold property.
     * 
     */
    public boolean isIsHold() {
        return isHold;
    }

    /**
     * Sets the value of the isHold property.
     * 
     */
    public void setIsHold(boolean value) {
        this.isHold = value;
    }

    /**
     * Gets the value of the isBackOrderAllow property.
     * 
     */
    public boolean isIsBackOrderAllow() {
        return isBackOrderAllow;
    }

    /**
     * Sets the value of the isBackOrderAllow property.
     * 
     */
    public void setIsBackOrderAllow(boolean value) {
        this.isBackOrderAllow = value;
    }

    /**
     * Gets the value of the isInternal property.
     * 
     */
    public boolean isIsInternal() {
        return isInternal;
    }

    /**
     * Sets the value of the isInternal property.
     * 
     */
    public void setIsInternal(boolean value) {
        this.isInternal = value;
    }

    /**
     * Gets the value of the isVolvo property.
     * 
     */
    public boolean isIsVolvo() {
        return isVolvo;
    }

    /**
     * Sets the value of the isVolvo property.
     * 
     */
    public void setIsVolvo(boolean value) {
        this.isVolvo = value;
    }

    /**
     * Gets the value of the isHotShot property.
     * 
     */
    public boolean isIsHotShot() {
        return isHotShot;
    }

    /**
     * Sets the value of the isHotShot property.
     * 
     */
    public void setIsHotShot(boolean value) {
        this.isHotShot = value;
    }

}
