//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 05:48:24 PM IST 
//


package com.pzv.dataload.model.dana.aftermarket.partmaster;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TotalPartsReceived" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="TotalPartsLoaded" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalPartsReceived",
    "totalPartsLoaded"
})
@XmlRootElement(name = "LoadPartMasterResponse")
public class LoadPartMasterResponse {

    @XmlElement(name = "TotalPartsReceived")
    protected long totalPartsReceived;
    @XmlElement(name = "TotalPartsLoaded")
    protected long totalPartsLoaded;

    /**
     * Gets the value of the totalPartsReceived property.
     * 
     */
    public long getTotalPartsReceived() {
        return totalPartsReceived;
    }

    /**
     * Sets the value of the totalPartsReceived property.
     * 
     */
    public void setTotalPartsReceived(long value) {
        this.totalPartsReceived = value;
    }

    /**
     * Gets the value of the totalPartsLoaded property.
     * 
     */
    public long getTotalPartsLoaded() {
        return totalPartsLoaded;
    }

    /**
     * Sets the value of the totalPartsLoaded property.
     * 
     */
    public void setTotalPartsLoaded(long value) {
        this.totalPartsLoaded = value;
    }

}
