//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 05:48:24 PM IST 
//


package com.pzv.dataload.model.dana.aftermarket.partmaster;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartMaster complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartMaster"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PartNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="PartStatus" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="SupersededPartNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Description01" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Description02" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProductHierarchy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PriceListGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RTBGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MinQty" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="PackageQty" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="UnitOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OEMFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LeadTimeInDays" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="IsReturnable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartMaster", propOrder = {
    "partNo",
    "isActive",
    "partStatus",
    "supersededPartNo",
    "description01",
    "description02",
    "category",
    "productHierarchy",
    "priceListGroup",
    "rtbGroup",
    "minQty",
    "packageQty",
    "unitOfMeasurement",
    "weight",
    "country",
    "oemFlag",
    "leadTimeInDays",
    "isReturnable"
})
public class PartMaster {

    @XmlElement(name = "PartNo", required = true)
    protected String partNo;
    @XmlElement(name = "IsActive")
    protected boolean isActive;
    @XmlElement(name = "PartStatus")
    protected short partStatus;
    @XmlElement(name = "SupersededPartNo", required = true)
    protected String supersededPartNo;
    @XmlElement(name = "Description01", required = true)
    protected String description01;
    @XmlElement(name = "Description02", required = true)
    protected String description02;
    @XmlElement(name = "Category", required = true)
    protected String category;
    @XmlElement(name = "ProductHierarchy", required = true)
    protected String productHierarchy;
    @XmlElement(name = "PriceListGroup", required = true)
    protected String priceListGroup;
    @XmlElement(name = "RTBGroup", required = true)
    protected String rtbGroup;
    @XmlElement(name = "MinQty")
    protected long minQty;
    @XmlElement(name = "PackageQty")
    protected long packageQty;
    @XmlElement(name = "UnitOfMeasurement", required = true)
    protected String unitOfMeasurement;
    @XmlElement(name = "Weight", required = true)
    protected BigDecimal weight;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "OEMFlag", required = true)
    protected String oemFlag;
    @XmlElement(name = "LeadTimeInDays")
    protected int leadTimeInDays;
    @XmlElement(name = "IsReturnable")
    protected boolean isReturnable;

    /**
     * Gets the value of the partNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartNo() {
        return partNo;
    }

    /**
     * Sets the value of the partNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartNo(String value) {
        this.partNo = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the partStatus property.
     * 
     */
    public short getPartStatus() {
        return partStatus;
    }

    /**
     * Sets the value of the partStatus property.
     * 
     */
    public void setPartStatus(short value) {
        this.partStatus = value;
    }

    /**
     * Gets the value of the supersededPartNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupersededPartNo() {
        return supersededPartNo;
    }

    /**
     * Sets the value of the supersededPartNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupersededPartNo(String value) {
        this.supersededPartNo = value;
    }

    /**
     * Gets the value of the description01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription01() {
        return description01;
    }

    /**
     * Sets the value of the description01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription01(String value) {
        this.description01 = value;
    }

    /**
     * Gets the value of the description02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription02() {
        return description02;
    }

    /**
     * Sets the value of the description02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription02(String value) {
        this.description02 = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the productHierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductHierarchy() {
        return productHierarchy;
    }

    /**
     * Sets the value of the productHierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductHierarchy(String value) {
        this.productHierarchy = value;
    }

    /**
     * Gets the value of the priceListGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceListGroup() {
        return priceListGroup;
    }

    /**
     * Sets the value of the priceListGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceListGroup(String value) {
        this.priceListGroup = value;
    }

    /**
     * Gets the value of the rtbGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRTBGroup() {
        return rtbGroup;
    }

    /**
     * Sets the value of the rtbGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRTBGroup(String value) {
        this.rtbGroup = value;
    }

    /**
     * Gets the value of the minQty property.
     * 
     */
    public long getMinQty() {
        return minQty;
    }

    /**
     * Sets the value of the minQty property.
     * 
     */
    public void setMinQty(long value) {
        this.minQty = value;
    }

    /**
     * Gets the value of the packageQty property.
     * 
     */
    public long getPackageQty() {
        return packageQty;
    }

    /**
     * Sets the value of the packageQty property.
     * 
     */
    public void setPackageQty(long value) {
        this.packageQty = value;
    }

    /**
     * Gets the value of the unitOfMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasurement() {
        return unitOfMeasurement;
    }

    /**
     * Sets the value of the unitOfMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasurement(String value) {
        this.unitOfMeasurement = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the oemFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOEMFlag() {
        return oemFlag;
    }

    /**
     * Sets the value of the oemFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOEMFlag(String value) {
        this.oemFlag = value;
    }

    /**
     * Gets the value of the leadTimeInDays property.
     * 
     */
    public int getLeadTimeInDays() {
        return leadTimeInDays;
    }

    /**
     * Sets the value of the leadTimeInDays property.
     * 
     */
    public void setLeadTimeInDays(int value) {
        this.leadTimeInDays = value;
    }

    /**
     * Gets the value of the isReturnable property.
     * 
     */
    public boolean isIsReturnable() {
        return isReturnable;
    }

    /**
     * Sets the value of the isReturnable property.
     * 
     */
    public void setIsReturnable(boolean value) {
        this.isReturnable = value;
    }

}
