//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.18 at 09:49:51 AM IST 
//


package com.pzv.dataload.model.dana.aftermarket.rtb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TotalRTBDetailsReceived" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="TotalRTBDetailsLoaded" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalRTBDetailsReceived",
    "totalRTBDetailsLoaded"
})
@XmlRootElement(name = "LoadRTBResponse")
public class LoadRTBResponse {

    @XmlElement(name = "TotalRTBDetailsReceived")
    protected long totalRTBDetailsReceived;
    @XmlElement(name = "TotalRTBDetailsLoaded")
    protected long totalRTBDetailsLoaded;

    /**
     * Gets the value of the totalRTBDetailsReceived property.
     * 
     */
    public long getTotalRTBDetailsReceived() {
        return totalRTBDetailsReceived;
    }

    /**
     * Sets the value of the totalRTBDetailsReceived property.
     * 
     */
    public void setTotalRTBDetailsReceived(long value) {
        this.totalRTBDetailsReceived = value;
    }

    /**
     * Gets the value of the totalRTBDetailsLoaded property.
     * 
     */
    public long getTotalRTBDetailsLoaded() {
        return totalRTBDetailsLoaded;
    }

    /**
     * Sets the value of the totalRTBDetailsLoaded property.
     * 
     */
    public void setTotalRTBDetailsLoaded(long value) {
        this.totalRTBDetailsLoaded = value;
    }

}
