//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 06:25:15 PM IST 
//


package com.pzv.dataload.model.dana.aftermarket.rtb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pzv.dataload.model.dana.aftermarket.rtb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pzv.dataload.model.dana.aftermarket.rtb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadRTBRequest }
     * 
     */
    public LoadRTBRequest createLoadRTBRequest() {
        return new LoadRTBRequest();
    }

    /**
     * Create an instance of {@link RTBDetail }
     * 
     */
    public RTBDetail createRTBDetail() {
        return new RTBDetail();
    }

    /**
     * Create an instance of {@link LoadRTBResponse }
     * 
     */
    public LoadRTBResponse createLoadRTBResponse() {
        return new LoadRTBResponse();
    }

}
